# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1
language: en

pipeline:
- name: SpacyNLP
  model: "en_core_web_trf"
  case_sensitive: true
- name: SpacyTokenizer
  intent_tokenization_flag: False 
  # intent_split_symbol: "/"
  token_pattern: None
- name: SpacyFeaturizer
  pooling: "mean"
# - name: RegexFeaturizer    
# - name: SpacyEntityExtractor
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  constrain_similarities: True
  # entity_recognition: False 
- name: SpacyEntityExtractor
  epochs: 40
- name: ResponseSelector
  epochs: 100
  retrieval_intent: human
- name: ResponseSelector
  epochs: 100
  retrieval_intent: loc
- name: ResponseSelector
  epochs: 100
  retrieval_intent: number
- name: ResponseSelector
  epochs: 100
    # constrain_similarities: true
  # - name: FallbackClassifier
  #   threshold: 0.3
  #   ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
  # - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1
  # - name: WhitespaceTokenizer
    # "intent_tokenization_flag": True
  # Symbol on which intent should be split
    # "intent_split_symbol": "/"
  # - name: RegexFeaturizer
  # - name: LexicalSyntacticFeaturizer
  # - name: CountVectorsFeaturizer
  # - name: CountVectorsFeaturizer
  #   analyzer: char_wb
  #   min_ngram: 1
  #   max_ngram: 4
  # - name: "SpacyNLP"
  # # language model to load
  #   model: "en_core_web_md"
  #   case_sensitive: False
  #   intent_tokenization_flag: True
  #   intent_split_symbol: "/"
  # - name: LanguageModelFeaturizer
  #   model_name: "bert"
  #   model_weights: "rasa/LaBSE"
  #   cache_dir: null
  # - name: DIETClassifier #By default entity_recognition and intent_classification are set to true
  #   epochs: 100
  #   ranking_length: 2
  #   use_masked_language_model: True
  #   constrain_similarities: true
  # - name: EntitySynonymMapper
  # - name: WhitespaceTokenizer
  # - name: RegexFeaturizer
  # - name: LexicalSyntacticFeaturizer
  # - name: CountVectorsFeaturizer
  # - name: CountVectorsFeaturizer
  #   analyzer: "char_wb"
  #   min_ngram: 1
  #   max_ngram: 4
  # - name: DIETClassifier
  #   epochs: 100
